# Generated by Django 4.0.2 on 2022-02-27 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('beginning', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(null=True, upload_to=main.models.user_directory_path, verbose_name='Фото')),
                ('geocode', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('award', models.IntegerField(default=0)),
                ('limiter', models.IntegerField(default=1)),
                ('complete', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('about', models.CharField(blank=True, max_length=256)),
                ('photo', models.ImageField(null=True, upload_to=main.models.user_directory_path, verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
